### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dveselov** [pullenti/pullenti-wrapper#1]
Привет, не знаю корректно ли размещать этот тикет здесь, но больше некуда его отправить, вроде бы.

Падает сам pulenti при разборе:
```
Traceback (most recent call last):
  File "mail.py", line 39, in <module>
    result = processor(content)
  File "~/dev/amnesia-annotators/env/lib64/python3.6/site-packages/pullenti_wrapper/processor.py", line 150, in __call__
    raw = self.raw.process(sofa)
  File "~/dev/amnesia-annotators/env/lib64/python3.6/site-packages/pullenti/ner/Processor.py", line 129, in process
    return self._process(text, False, False, ext_ontology, lang)
  File "~/dev/amnesia-annotators/env/lib64/python3.6/site-packages/pullenti/ner/Processor.py", line 175, in _process
    self.__process(kit, ar, no_log)
  File "~/dev/amnesia-annotators/env/lib64/python3.6/site-packages/pullenti/ner/Processor.py", line 230, in __process
    c.process(kit)
  File "~/dev/amnesia-annotators/env/lib64/python3.6/site-packages/pullenti/ner/person/PersonAnalyzer.py", line 287, in process
    rt.referent = ad.register_referent(rt.referent)
  File "~/dev/amnesia-annotators/env/lib64/python3.6/site-packages/pullenti/ner/person/PersonAnalyzer.py", line 106, in register_referent
    res = super().register_referent(referent)
  File "~/dev/amnesia-annotators/env/lib64/python3.6/site-packages/pullenti/ner/core/AnalyzerDataWithOntology.py", line 27, in register_referent
    res.merge_slots(referent, True)
  File "~/dev/amnesia-annotators/env/lib64/python3.6/site-packages/pullenti/ner/person/PersonReferent.py", line 607, in merge_slots
    self._correct_data()
  File ~/dev/amnesia-annotators/env/lib64/python3.6/site-packages/pullenti/ner/person/PersonReferent.py", line 641, in _correct_data
    self.__correct_identifiers()
  File "~/dev/amnesia-annotators/env/lib64/python3.6/site-packages/pullenti/ner/person/PersonReferent.py", line 678, in __correct_identifiers
    if (self.slots[i].type_name == PersonReferent.ATTR_IDENTITY): 
IndexError: list index out of range
```

```
content = '''Кроссовки adidas NMD стали самой популярной моделью в Instagram, сообщает The Independent. Согласно исследованию, проведенному британской логистической компанией Forward2me, на данный момент фотографии этой модели появлялись в соцсети более 5,7 миллиона раз. На втором месте оказались кроссовки Yeezy 350, созданные тем же производителем в коллаборации с брендом рэпера и дизайнера Канье Уэста. В них пользователи сфотографировались 4,1 миллиона раз. Следующими по «фотографируемости» стали Vans Old Skool с 3,6 миллиона публикаций и Adidas Superstars (3,4 миллиона). Пятое место заняли классические кеды Converse Chuck Taylor All Star. Они попали на снимки пользователей более двух миллионов раз. В июне Канье Уэст пригласил порнозвезд сняться в рекламной кампании своих новых кроссовок Yeezy 500 Supermoon Yellow. Модель прорекламировали участницы реалити-шоу Bad Girls Club, сестры Clermont Twins, колумнистка Кристен Ноэль Кроули, порноактриса Лела Стар, похожая на жену рэпера Ким Кардашьян, и другие ее коллеги.'''
result = processor(content)
```

**Comment by kuk** [comment]
Да, бывает такое. В обёртке думаю можно только обернуть в `try except IndexError`. По-моему эта ошибка происходит редко.

@konstantin-smith , можете добавить пример себе в юнит-тесты.

**Comment by konstantin-smith** [comment]
Лучше всё-таки исправлять. Видимо, это от ошибок конвертера, недавно выложил на сайт новую версию Pullenti, на ней эта ошибка не проявляется. Обновите SDK с pullenti.ru

**Comment by konstantin-smith** [comment]
Вообще то странно, как может возникнуть исключение в таком коде, как i в принципе может выйти за границу массива ??? :
        i = 0
        while i < len(self.slots): 
            if (self.slots[i].type_name == PersonReferent.ATTR_IDENTITY):

**Comment by kuk** [comment]
@konstantin-smith здорово! может быть `self.slots` где-то меняет свой размер
@dveselov `pip install pullenti-wrapper==0.2.0` , должно работать
